GET http://localhost:5214/games


###

GET http://localhost:5214/games/3

###

POST http://localhost:5214/games
Content-Type: application/json

{
    "name" : "Big game",
    "genreId" : 2,
    "price" : 1000.00,
    "releaseDate" : "2012-01-01"
}

###
PUT http://localhost:5214/games/2
Content-Type: application/json

{
     "name" : "Homeless vs Rich",
    "genreId" : 1,
    "price" : 102.00,
    "releaseDate" : "2020-01-01"
}

###

DELETE http://localhost:5214/games/1

###

GET http://localhost:5214/genres

